<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  
  
  
    <meta name="description" content="Ain&#39;t no mountain high enough">
  
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <title>
    pythonocc入门 |
    
    Blog_JosephLZD</title>
  
    <link rel="shortcut icon" href="/favicon.ico">
  
  
<link rel="stylesheet" href="/css/style.css">

  
    
<link rel="stylesheet" href="/fancybox/jquery.fancybox.min.css">

  
  
<script src="/js/pace.min.js"></script>

<meta name="generator" content="Hexo 4.1.1"></head>

<body>
<main class="content">
  <section class="outer">
  

<article id="post-pythonocc入门" class="article article-type-post" itemscope itemprop="blogPost" data-scroll-reveal>
  
  <div class="article-inner">
    
      <header class="article-header">
        
  
    <h1 class="article-title" itemprop="name">
      pythonocc入门
    </h1>
  
  




      </header>
    

    
      <div class="article-meta">
        <a href="/2020/04/10/pythonocc%E5%85%A5%E9%97%A8/" class="article-date">
  <time datetime="2020-04-10T09:45:44.000Z" itemprop="datePublished">2020-04-10</time>
</a>
        
      </div>
    

    
      
    <div class="tocbot"></div>





    

    <div class="article-entry" itemprop="articleBody">
      


      

      
        <p>pythonocc初步学习，包括创建球体、圆柱体和圆锥体，以及布尔运算。</p>
<a id="more"></a>

<p><strong>casually speaking:</strong></p>
<p>周导发来消息：<br>pythonocc抽空可以熟悉一下，实验室后面会有些相关的项目，涉及一些<strong>3d对象的管理和简单的几何编辑修改功能</strong>。好的，这个需要一些几何知识，pythonocc occ是一个非常著名的几何引擎。你可以先跑跑demo，学习体验一下[强]</p>
<p>于是，我准备4.3-4.6抓紧学习熟悉，争取4.7向他汇报一下进度，毕竟宜早不宜迟嘛。</p>
<p>如果能够尽快把这个项目所需的技能熟悉起来，之后做项目肯定轻松一些。虽然我目前的想法是带着一个自己上个月跑出来的实验结果（抑郁emoji强化学习）去研一找周导发论文，但作为专硕，还是需要听从老师安排去做项目。我觉得这不是坏事，很多学硕天天愁论文，因为实在没有可视化成果，而我边做着项目，边想着发论文，因为有项目进度和成果这种可视化的东西，我自己也不会很焦虑。尽管累一点，但是值得。我相信专硕期间我能够在保持学习成绩的情况下，把项目和科研都完成好，争取拿到奖学金。至于实验室里其他同学他们的论文，我能否蹭一下呢？我觉得主要是看我能不能起到帮助，前提是首先我们关系处好，最重要的是我能够有相应的知识储备、帮上忙。</p>
<p>所以，我准备4.7-4.9把周导实验室在19年发的3篇论文拿出来精读一下，看看里面用到的方法大概是怎么样的，之后学习也可以更有针对性一点。毕竟现在实验室可能大多还是有”传承成果“的情况（比如我这本科毕设高老师这边）。</p>
<p>同时，4.7之后我要开始抓紧继续完善毕设了。其实我目前毕设工程设计我觉得真的太简单了，根本没有值得一提的东西，而算法又非重点，我觉得就像张老师说的那样，考虑多信息，可以体现工作量，同时看看框架还有没有需要完善的地方，工程设计上的理论基础打好（我觉得主要是那种老师都知道的工程项目框架经典知识），才能在答辩时经得起问啊（而且可以提前询问高老师，让他提前模拟答辩我）。</p>
<br>

<h1 id="简介"><a href="#简介" class="headerlink" title="简介"></a>简介</h1><p>pythonOCC是python语言构架的 3D CAD/CAE/PLM开发框架，它提供了如下功能： 复杂曲面的操作，信息转换（STEP,IGES,STL格式），用户界面可视化（基于wxpython库或者qt库），jupyter nootbook生成等。</p>
<blockquote>
<p>CAD: Computer Aided Design，计算机辅助设计，主要还是用作图、编辑图形的。</p>
</blockquote>
<p><strong>能够提供如下操作</strong>：<br>2D和3D几何建模工具包让我们能够对任何类型的对象进行建模：</p>
<p>创建基本体，如棱柱、圆柱、圆锥、圆环面<br>布尔操作（交、并、补）<br>倒角、倒圆角与草图操作<br>平移、抽壳、打孔和扫略建模<br>计算属性，如表面面积，体积，重心和曲率<br>进行投影、插补和近似操作<br>可视化模块能够让你管理模型的显示，以及操作视图。</p>
<h1 id="代码框架"><a href="#代码框架" class="headerlink" title="代码框架"></a>代码框架</h1><p>首先，代码1：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> sys</span><br><span class="line"><span class="keyword">from</span> OCC.Display.SimpleGui <span class="keyword">import</span> *</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">draw_nothing</span><span class="params">(event=None)</span>:</span></span><br><span class="line">    <span class="keyword">pass</span></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">exit</span><span class="params">(event=None)</span>:</span></span><br><span class="line">    sys.exit()</span><br><span class="line"></span><br><span class="line"><span class="keyword">if</span> __name__ == <span class="string">'__main__'</span>:</span><br><span class="line">    display, start_display, add_menu, add_function_to_menu = init_display()  <span class="comment"># OCC.Display.SimpleGui.init_display()返回四个函数</span></span><br><span class="line">    <span class="comment">#四个函数分别是：display, start_display用于开启，add_menu用于增加菜单栏选项，add_funciton_to_menu用于给选项下拉框加选项（功能）</span></span><br><span class="line">    add_menu(<span class="string">"File"</span>)</span><br><span class="line">    add_function_to_menu(<span class="string">'File'</span>,exit) <span class="comment">#参数1是菜单选项名，参数2是自定义的函数名，注意不加括号呀！！</span></span><br><span class="line">    add_menu(<span class="string">"Draw"</span>)</span><br><span class="line">    add_function_to_menu(<span class="string">'Draw'</span>,draw_nothing)</span><br><span class="line"></span><br><span class="line">    start_display()</span><br></pre></td></tr></table></figure>
<p><img src="https://imgvideoforblog.oss-cn-shanghai.aliyuncs.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202020-04-06%20%E4%B8%8B%E5%8D%886.12.31.png" alt="alt"><br>注意我mac电脑显示的时候菜单栏会跑到电脑屏幕顶端，而且要来回切到后台，菜单栏点了才有反应，或者页面的东西才会有动态变化。</p>
<p><strong>关于操作：左键按住是调视角，右键（双指）按住往左是放大往右是缩小，滑动是上下平移</strong>。</p>
<br>
# 球体
Extending the Menu

<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br><span class="line">55</span><br><span class="line">56</span><br><span class="line">57</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> sys</span><br><span class="line"><span class="keyword">from</span> OCC.Display.SimpleGui <span class="keyword">import</span> *</span><br><span class="line"><span class="keyword">from</span> OCC.Core.BRepPrimAPI <span class="keyword">import</span> *</span><br><span class="line"><span class="keyword">from</span> OCC.Core.gp <span class="keyword">import</span> *</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">draw_nothing</span><span class="params">(event=None)</span>:</span></span><br><span class="line">    <span class="keyword">pass</span></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">exit</span><span class="params">(event=None)</span>:</span></span><br><span class="line">    sys.exit()</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">draw_sphere_1</span><span class="params">(event=None)</span>:</span></span><br><span class="line">    <span class="comment">#创建球体的半径和圆心位置</span></span><br><span class="line">    R = <span class="number">50.0</span></span><br><span class="line">    X1=<span class="number">0.0</span></span><br><span class="line">    Y1=<span class="number">0.0</span></span><br><span class="line">    Z1=<span class="number">0.0</span></span><br><span class="line"></span><br><span class="line">    <span class="comment">#通过OCC.Core.gp的gp_Pnt函数来把它变成空间中的一个点</span></span><br><span class="line">    Point = gp_Pnt(X1, Y1, Z1)</span><br><span class="line">    MySphere = BRepPrimAPI_MakeSphere(Point, R) <span class="comment">#传入圆心和半径</span></span><br><span class="line"></span><br><span class="line">    <span class="comment">#获取它的Shape，从而通过display的函数来上色</span></span><br><span class="line">    MySphereShape = MySphere.Shape()</span><br><span class="line">    display.DisplayColoredShape(MySphereShape, <span class="string">'RED'</span>) <span class="comment">#第二个参数是颜色的字符串</span></span><br><span class="line"></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">draw_sphere_2</span><span class="params">(event=None)</span>:</span></span><br><span class="line">    <span class="comment"># 创建球体的半径和圆心位置</span></span><br><span class="line">    R = <span class="number">50.0</span></span><br><span class="line">    X1 = <span class="number">25.0</span></span><br><span class="line">    Y1 = <span class="number">50.0</span></span><br><span class="line">    Z1 = <span class="number">50.0</span></span><br><span class="line"></span><br><span class="line">    <span class="comment"># 通过OCC.Core.gp的gp_Pnt函数来把它变成空间中的一个点</span></span><br><span class="line">    Point = gp_Pnt(X1, Y1, Z1)</span><br><span class="line">    MySphere = BRepPrimAPI_MakeSphere(Point, R)  <span class="comment"># 传入圆心和半径</span></span><br><span class="line"></span><br><span class="line">    <span class="comment"># 获取它的Shape，从而通过display的函数来上色</span></span><br><span class="line">    MySphereShape = MySphere.Shape()</span><br><span class="line">    display.DisplayColoredShape(MySphereShape, <span class="string">'YELLOW'</span>)  <span class="comment"># 第二个参数是颜色的字符串</span></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">erase_all</span><span class="params">(event=None)</span>:</span></span><br><span class="line">    display.EraseAll() <span class="comment">#display直接去除所有</span></span><br><span class="line"></span><br><span class="line"><span class="keyword">if</span> __name__ == <span class="string">'__main__'</span>:</span><br><span class="line">    display, start_display, add_menu, add_function_to_menu = init_display()  <span class="comment"># OCC.Display.SimpleGui.init_display()返回四个函数</span></span><br><span class="line">    <span class="comment">#四个函数分别是：display, start_display用于开启，add_menu用于增加菜单栏选项，add_funciton_to_menu用于给选项设置相应功能</span></span><br><span class="line">    add_menu(<span class="string">"File"</span>)</span><br><span class="line">    add_function_to_menu(<span class="string">'File'</span>,exit) <span class="comment">#参数1是菜单选项名，参数2是自定义的函数名，注意不加括号</span></span><br><span class="line">    add_menu(<span class="string">"Draw"</span>)</span><br><span class="line">    add_function_to_menu(<span class="string">'Draw'</span>,draw_sphere_1)</span><br><span class="line">    add_function_to_menu(<span class="string">'Draw'</span>,draw_sphere_2) <span class="comment">#连续对同一选项add多次功能，即下拉框有多个选项！</span></span><br><span class="line">    add_menu(<span class="string">'Erase'</span>)</span><br><span class="line">    add_function_to_menu(<span class="string">'Erase'</span>,erase_all)</span><br><span class="line"></span><br><span class="line">    start_display()</span><br></pre></td></tr></table></figure>
<br>

<h2 id="scipy向量"><a href="#scipy向量" class="headerlink" title="scipy向量"></a>scipy向量</h2><p>把创建球体的操作封装起来，且用<strong>scipy向量</strong>来简化球心位置的赋值。</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> scipy</span><br><span class="line"><span class="keyword">import</span> sys</span><br><span class="line"><span class="keyword">from</span> OCC.Display.SimpleGui <span class="keyword">import</span> *</span><br><span class="line"><span class="keyword">from</span> OCC.Core.BRepPrimAPI <span class="keyword">import</span> *</span><br><span class="line"><span class="keyword">from</span> OCC.Core.gp <span class="keyword">import</span> *</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">draw_nothing</span><span class="params">(event=None)</span>:</span></span><br><span class="line">    <span class="keyword">pass</span></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">exit</span><span class="params">(event=None)</span>:</span></span><br><span class="line">    sys.exit()</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">sphere_from_vector_and_scalar</span><span class="params">(vector, radius)</span>:</span></span><br><span class="line">    <span class="string">'''</span></span><br><span class="line"><span class="string">    把创建球体的操作封装起来，且用scipy向量来简化球心位置的赋值</span></span><br><span class="line"><span class="string">    直接传入球心的位置向量，半径，返回一个球体.</span></span><br><span class="line"><span class="string">    :param vector: scipy向量，维度为（3，1）</span></span><br><span class="line"><span class="string">    :param radius: 半径，一个标量</span></span><br><span class="line"><span class="string">    :return: 球体</span></span><br><span class="line"><span class="string">    '''</span></span><br><span class="line">    X1 = float( vector[<span class="number">0</span>,<span class="number">0</span>] )</span><br><span class="line">    Y1 = float( vector[<span class="number">1</span>,<span class="number">0</span>] )</span><br><span class="line">    Z1 = float( vector[<span class="number">2</span>,<span class="number">0</span>] )</span><br><span class="line">    Point = gp_Pnt(X1, Y1, Z1)</span><br><span class="line">    sphere = BRepPrimAPI_MakeSphere(Point, radius)</span><br><span class="line">    <span class="keyword">return</span> sphere</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">draw_sphere_1</span><span class="params">(event=None)</span>:</span></span><br><span class="line">    <span class="comment">#半径</span></span><br><span class="line">    radius = <span class="number">50.0</span></span><br><span class="line">    <span class="comment">#球心位置 创建向量</span></span><br><span class="line">    PointZeroArray = scipy.zeros((<span class="number">3</span>,<span class="number">1</span>), dtype=float) <span class="comment">#(0;0;0) 创建scipy向量</span></span><br><span class="line">    MySphere = sphere_from_vector_and_scalar(PointZeroArray, radius)</span><br><span class="line"></span><br><span class="line">    <span class="comment">#获取它的Shape，从而通过display的函数来上色</span></span><br><span class="line">    MySphereShape = MySphere.Shape()</span><br><span class="line">    display.DisplayColoredShape(MySphereShape, <span class="string">'RED'</span>) <span class="comment">#第二个参数是颜色的字符串</span></span><br><span class="line"></span><br><span class="line"></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">erase_all</span><span class="params">(event=None)</span>:</span></span><br><span class="line">    display.EraseAll() <span class="comment">#display直接去除所有</span></span><br><span class="line"></span><br><span class="line"><span class="keyword">if</span> __name__ == <span class="string">'__main__'</span>:</span><br><span class="line">    display, start_display, add_menu, add_function_to_menu = init_display()  <span class="comment"># OCC.Display.SimpleGui.init_display()返回四个函数</span></span><br><span class="line">    <span class="comment">#四个函数分别是：display, start_display用于开启，add_menu用于增加菜单栏选项，add_funciton_to_menu用于给选项设置相应功能</span></span><br><span class="line">    add_menu(<span class="string">"File"</span>)</span><br><span class="line">    add_function_to_menu(<span class="string">'File'</span>,exit) <span class="comment">#参数1是菜单选项名，参数2是自定义的函数名，注意不加括号</span></span><br><span class="line">    add_menu(<span class="string">"Draw"</span>)</span><br><span class="line">    add_function_to_menu(<span class="string">'Draw'</span>,draw_sphere_1)</span><br><span class="line">    add_menu(<span class="string">'Erase'</span>)</span><br><span class="line">    add_function_to_menu(<span class="string">'Erase'</span>,erase_all)</span><br><span class="line"></span><br><span class="line">    start_display()</span><br></pre></td></tr></table></figure>
<br>

<h1 id="布尔运算"><a href="#布尔运算" class="headerlink" title="布尔运算"></a>布尔运算</h1><p><strong>布尔运算，即交并补运算</strong>。<br>我们通过现有的函数API来实现两个球体的交并补。</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br><span class="line">55</span><br><span class="line">56</span><br><span class="line">57</span><br><span class="line">58</span><br><span class="line">59</span><br><span class="line">60</span><br><span class="line">61</span><br><span class="line">62</span><br><span class="line">63</span><br><span class="line">64</span><br><span class="line">65</span><br><span class="line">66</span><br><span class="line">67</span><br><span class="line">68</span><br><span class="line">69</span><br><span class="line">70</span><br><span class="line">71</span><br><span class="line">72</span><br><span class="line">73</span><br><span class="line">74</span><br><span class="line">75</span><br><span class="line">76</span><br><span class="line">77</span><br><span class="line">78</span><br><span class="line">79</span><br><span class="line">80</span><br><span class="line">81</span><br><span class="line">82</span><br><span class="line">83</span><br><span class="line">84</span><br><span class="line">85</span><br><span class="line">86</span><br><span class="line">87</span><br><span class="line">88</span><br><span class="line">89</span><br><span class="line">90</span><br><span class="line">91</span><br><span class="line">92</span><br><span class="line">93</span><br><span class="line">94</span><br><span class="line">95</span><br><span class="line">96</span><br><span class="line">97</span><br><span class="line">98</span><br><span class="line">99</span><br><span class="line">100</span><br><span class="line">101</span><br><span class="line">102</span><br><span class="line">103</span><br><span class="line">104</span><br><span class="line">105</span><br><span class="line">106</span><br><span class="line">107</span><br><span class="line">108</span><br><span class="line">109</span><br><span class="line">110</span><br><span class="line">111</span><br><span class="line">112</span><br><span class="line">113</span><br><span class="line">114</span><br><span class="line">115</span><br><span class="line">116</span><br><span class="line">117</span><br><span class="line">118</span><br><span class="line">119</span><br><span class="line">120</span><br><span class="line">121</span><br><span class="line">122</span><br><span class="line">123</span><br><span class="line">124</span><br><span class="line">125</span><br><span class="line">126</span><br><span class="line">127</span><br><span class="line">128</span><br><span class="line">129</span><br><span class="line">130</span><br><span class="line">131</span><br><span class="line">132</span><br><span class="line">133</span><br><span class="line">134</span><br><span class="line">135</span><br><span class="line">136</span><br><span class="line">137</span><br><span class="line">138</span><br><span class="line">139</span><br><span class="line">140</span><br><span class="line">141</span><br><span class="line">142</span><br><span class="line">143</span><br><span class="line">144</span><br><span class="line">145</span><br><span class="line">146</span><br><span class="line">147</span><br><span class="line">148</span><br><span class="line">149</span><br><span class="line">150</span><br><span class="line">151</span><br><span class="line">152</span><br><span class="line">153</span><br><span class="line">154</span><br><span class="line">155</span><br><span class="line">156</span><br><span class="line">157</span><br><span class="line">158</span><br><span class="line">159</span><br><span class="line">160</span><br><span class="line">161</span><br><span class="line">162</span><br><span class="line">163</span><br><span class="line">164</span><br><span class="line">165</span><br><span class="line">166</span><br><span class="line">167</span><br><span class="line">168</span><br><span class="line">169</span><br><span class="line">170</span><br><span class="line">171</span><br><span class="line">172</span><br><span class="line">173</span><br><span class="line">174</span><br><span class="line">175</span><br><span class="line">176</span><br><span class="line">177</span><br><span class="line">178</span><br><span class="line">179</span><br><span class="line">180</span><br><span class="line">181</span><br><span class="line">182</span><br><span class="line">183</span><br><span class="line">184</span><br><span class="line">185</span><br><span class="line">186</span><br><span class="line">187</span><br><span class="line">188</span><br><span class="line">189</span><br><span class="line">190</span><br><span class="line">191</span><br><span class="line">192</span><br><span class="line">193</span><br><span class="line">194</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> scipy</span><br><span class="line"><span class="keyword">import</span> sys</span><br><span class="line"><span class="keyword">from</span> OCC.Display.SimpleGui <span class="keyword">import</span> *</span><br><span class="line"><span class="keyword">from</span> OCC.Core.BRepPrimAPI <span class="keyword">import</span> *</span><br><span class="line"><span class="keyword">from</span> OCC.Core.BRepAlgoAPI <span class="keyword">import</span> *</span><br><span class="line"><span class="keyword">from</span> OCC.Core.gp <span class="keyword">import</span> *</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">draw_nothing</span><span class="params">(event=None)</span>:</span></span><br><span class="line">    <span class="keyword">pass</span></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">exit</span><span class="params">(event=None)</span>:</span></span><br><span class="line">    sys.exit()</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">sphere_from_vector_and_scalar</span><span class="params">(vector, radius)</span>:</span></span><br><span class="line">    <span class="string">'''</span></span><br><span class="line"><span class="string">    把创建球体的操作封装起来，且用scipy向量来简化球心位置的赋值</span></span><br><span class="line"><span class="string">    直接传入球心的位置向量，半径，返回一个球体.</span></span><br><span class="line"><span class="string">    :param vector: scipy向量，维度为（3，1）</span></span><br><span class="line"><span class="string">    :param radius: 半径，一个标量</span></span><br><span class="line"><span class="string">    :return: 球体</span></span><br><span class="line"><span class="string">    '''</span></span><br><span class="line">    X1 = float( vector[<span class="number">0</span>,<span class="number">0</span>] )</span><br><span class="line">    Y1 = float( vector[<span class="number">1</span>,<span class="number">0</span>] )</span><br><span class="line">    Z1 = float( vector[<span class="number">2</span>,<span class="number">0</span>] )</span><br><span class="line">    Point = gp_Pnt(X1, Y1, Z1)</span><br><span class="line">    sphere = BRepPrimAPI_MakeSphere(Point, radius)</span><br><span class="line">    <span class="keyword">return</span> sphere</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">draw_sphere_1</span><span class="params">(event=None)</span>:</span></span><br><span class="line">    <span class="comment">#半径</span></span><br><span class="line">    radius = <span class="number">50.0</span></span><br><span class="line">    <span class="comment">#球心位置 创建向量</span></span><br><span class="line">    PointZeroArray = scipy.zeros((<span class="number">3</span>,<span class="number">1</span>), dtype=float) <span class="comment">#(0;0;0) 创建scipy向量</span></span><br><span class="line">    MySphere = sphere_from_vector_and_scalar(PointZeroArray, radius)</span><br><span class="line"></span><br><span class="line">    <span class="comment">#获取它的Shape，从而通过display的函数来上色</span></span><br><span class="line">    MySphereShape = MySphere.Shape()</span><br><span class="line">    display.DisplayColoredShape(MySphereShape, <span class="string">'RED'</span>) <span class="comment">#第二个参数是颜色的字符串</span></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">draw_sphere_2</span><span class="params">(event=None)</span>:</span></span><br><span class="line">    <span class="comment">#半径</span></span><br><span class="line">    radius = <span class="number">50.0</span></span><br><span class="line">    <span class="comment">#球心位置 创建向量</span></span><br><span class="line">    PointArray = scipy.array([<span class="number">25</span>,<span class="number">50</span>,<span class="number">50</span>], dtype=float) <span class="comment">#创建scipy向量</span></span><br><span class="line">    <span class="comment">#注意：这个向量现在是（1，3），我们需要reshape成（3，1）</span></span><br><span class="line">    PointArray = scipy.reshape(PointArray, (<span class="number">3</span>,<span class="number">1</span>))</span><br><span class="line">    MySphere = sphere_from_vector_and_scalar(PointArray, radius)</span><br><span class="line"></span><br><span class="line">    <span class="comment">#获取它的Shape，从而通过display的函数来上色</span></span><br><span class="line">    MySphereShape = MySphere.Shape()</span><br><span class="line">    display.DisplayColoredShape(MySphereShape, <span class="string">'YELLOW'</span>) <span class="comment">#第二个参数是颜色的字符串</span></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">draw_fused_spheres</span><span class="params">(event=None)</span>:</span></span><br><span class="line">    <span class="string">'''</span></span><br><span class="line"><span class="string">    运用API来做两个球体的并集 ∪</span></span><br><span class="line"><span class="string">    '''</span></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">draw_cutted_spheres_1</span><span class="params">(event=None)</span>:</span></span><br><span class="line">    <span class="string">'''</span></span><br><span class="line"><span class="string">    运用API来做两个球体的差集 -</span></span><br><span class="line"><span class="string">    先生成两个球体，然后再把它们的Shape作为参数传入API函数，进行显示</span></span><br><span class="line"><span class="string">    注意参数顺序不同效果不同。第一个参数是前者A，第二个参数是后者B，运算是A-B</span></span><br><span class="line"><span class="string">    '''</span></span><br><span class="line">    <span class="comment">#首先清空display</span></span><br><span class="line">    display.EraseAll()</span><br><span class="line"></span><br><span class="line">    <span class="comment"># 第一个球体</span></span><br><span class="line">    radius = <span class="number">50.0</span></span><br><span class="line">    <span class="comment"># 球心位置 创建向量</span></span><br><span class="line">    PointZeroArray = scipy.zeros((<span class="number">3</span>, <span class="number">1</span>), dtype=float)  <span class="comment"># (0;0;0) 创建scipy向量</span></span><br><span class="line">    MySphere = sphere_from_vector_and_scalar(PointZeroArray, radius)</span><br><span class="line">    <span class="comment"># 获取它的Shape，从而通过display的函数来上色</span></span><br><span class="line">    MySphereShape_1 = MySphere.Shape()</span><br><span class="line"></span><br><span class="line">    <span class="comment"># 第二个球体</span></span><br><span class="line">    PointArray = scipy.array([<span class="number">25</span>, <span class="number">50</span>, <span class="number">50</span>], dtype=float)  <span class="comment"># 创建scipy向量</span></span><br><span class="line">    <span class="comment"># 注意：这个向量现在是（1，3），我们需要reshape成（3，1）</span></span><br><span class="line">    PointArray = scipy.reshape(PointArray, (<span class="number">3</span>, <span class="number">1</span>))</span><br><span class="line">    MySphere = sphere_from_vector_and_scalar(PointArray, radius)</span><br><span class="line">    <span class="comment"># 获取它的Shape，从而通过display的函数来上色</span></span><br><span class="line">    MySphereShape_2 = MySphere.Shape()</span><br><span class="line"></span><br><span class="line">    CuttedSpheres = BRepAlgoAPI_Cut(MySphereShape_1, MySphereShape_2)</span><br><span class="line">    CuttedSpheres_shape = CuttedSpheres.Shape()</span><br><span class="line"></span><br><span class="line">    display.DisplayColoredShape(CuttedSpheres_shape, <span class="string">"BLUE"</span>)</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">draw_cutted_spheres_2</span><span class="params">(event=None)</span>:</span></span><br><span class="line">    <span class="string">'''</span></span><br><span class="line"><span class="string">    运用API来做两个球体的差集 -</span></span><br><span class="line"><span class="string">    由于差集分先后！所以交换参数顺序，是不一样的。</span></span><br><span class="line"><span class="string">    '''</span></span><br><span class="line">    <span class="comment">#首先清空display</span></span><br><span class="line">    display.EraseAll()</span><br><span class="line"></span><br><span class="line">    <span class="comment"># 第一个球体</span></span><br><span class="line">    radius = <span class="number">50.0</span></span><br><span class="line">    <span class="comment"># 球心位置 创建向量</span></span><br><span class="line">    PointZeroArray = scipy.zeros((<span class="number">3</span>, <span class="number">1</span>), dtype=float)  <span class="comment"># (0;0;0) 创建scipy向量</span></span><br><span class="line">    MySphere = sphere_from_vector_and_scalar(PointZeroArray, radius)</span><br><span class="line">    <span class="comment"># 获取它的Shape，从而通过display的函数来上色</span></span><br><span class="line">    MySphereShape_1 = MySphere.Shape()</span><br><span class="line"></span><br><span class="line">    <span class="comment"># 第二个球体</span></span><br><span class="line">    PointArray = scipy.array([<span class="number">25</span>, <span class="number">50</span>, <span class="number">50</span>], dtype=float)  <span class="comment"># 创建scipy向量</span></span><br><span class="line">    <span class="comment"># 注意：这个向量现在是（1，3），我们需要reshape成（3，1）</span></span><br><span class="line">    PointArray = scipy.reshape(PointArray, (<span class="number">3</span>, <span class="number">1</span>))</span><br><span class="line">    MySphere = sphere_from_vector_and_scalar(PointArray, radius)</span><br><span class="line">    <span class="comment"># 获取它的Shape，从而通过display的函数来上色</span></span><br><span class="line">    MySphereShape_2 = MySphere.Shape()</span><br><span class="line"></span><br><span class="line">    CuttedSpheres = BRepAlgoAPI_Cut(MySphereShape_2, MySphereShape_1) <span class="comment">#这里交换参数顺序</span></span><br><span class="line">    CuttedSpheres_shape = CuttedSpheres.Shape()</span><br><span class="line"></span><br><span class="line">    display.DisplayColoredShape(CuttedSpheres_shape, <span class="string">"BLUE"</span>)</span><br><span class="line"></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">draw_common_spheres</span><span class="params">(event=None)</span>:</span></span><br><span class="line">    <span class="string">'''</span></span><br><span class="line"><span class="string">    common:交集 ∩</span></span><br><span class="line"><span class="string">    '''</span></span><br><span class="line">    display.EraseAll()</span><br><span class="line"></span><br><span class="line">    <span class="comment"># 第一个球体</span></span><br><span class="line">    radius = <span class="number">50.0</span></span><br><span class="line">    <span class="comment"># 球心位置 创建向量</span></span><br><span class="line">    PointZeroArray = scipy.zeros((<span class="number">3</span>, <span class="number">1</span>), dtype=float)  <span class="comment"># (0;0;0) 创建scipy向量</span></span><br><span class="line">    MySphere = sphere_from_vector_and_scalar(PointZeroArray, radius)</span><br><span class="line">    <span class="comment"># 获取它的Shape，从而通过display的函数来上色</span></span><br><span class="line">    MySphereShape_1 = MySphere.Shape()</span><br><span class="line"></span><br><span class="line">    <span class="comment"># 第二个球体</span></span><br><span class="line">    PointArray = scipy.array([<span class="number">25</span>, <span class="number">50</span>, <span class="number">50</span>], dtype=float)  <span class="comment"># 创建scipy向量</span></span><br><span class="line">    <span class="comment"># 注意：这个向量现在是（1，3），我们需要reshape成（3，1）</span></span><br><span class="line">    PointArray = scipy.reshape(PointArray, (<span class="number">3</span>, <span class="number">1</span>))</span><br><span class="line">    MySphere = sphere_from_vector_and_scalar(PointArray, radius)</span><br><span class="line">    <span class="comment"># 获取它的Shape，从而通过display的函数来上色</span></span><br><span class="line">    MySphereShape_2 = MySphere.Shape()</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">    CommonSpheres = BRepAlgoAPI_Common(MySphereShape_1, MySphereShape_2)</span><br><span class="line">    CommonSpheres_shape = CommonSpheres.Shape()</span><br><span class="line"></span><br><span class="line">    display.DisplayColoredShape(CommonSpheres_shape, <span class="string">"GREEN"</span>)</span><br><span class="line"></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">draw_fused_spheres</span><span class="params">(event=None)</span>:</span></span><br><span class="line">    <span class="string">'''</span></span><br><span class="line"><span class="string">    fused: 并集 ∪</span></span><br><span class="line"><span class="string">    '''</span></span><br><span class="line">    display.EraseAll()</span><br><span class="line"></span><br><span class="line">    <span class="comment"># 第一个球体</span></span><br><span class="line">    radius = <span class="number">50.0</span></span><br><span class="line">    <span class="comment"># 球心位置 创建向量</span></span><br><span class="line">    PointZeroArray = scipy.zeros((<span class="number">3</span>, <span class="number">1</span>), dtype=float)  <span class="comment"># (0;0;0) 创建scipy向量</span></span><br><span class="line">    MySphere = sphere_from_vector_and_scalar(PointZeroArray, radius)</span><br><span class="line">    <span class="comment"># 获取它的Shape，从而通过display的函数来上色</span></span><br><span class="line">    MySphereShape_1 = MySphere.Shape()</span><br><span class="line"></span><br><span class="line">    <span class="comment"># 第二个球体</span></span><br><span class="line">    PointArray = scipy.array([<span class="number">25</span>, <span class="number">50</span>, <span class="number">50</span>], dtype=float)  <span class="comment"># 创建scipy向量</span></span><br><span class="line">    <span class="comment"># 注意：这个向量现在是（1，3），我们需要reshape成（3，1）</span></span><br><span class="line">    PointArray = scipy.reshape(PointArray, (<span class="number">3</span>, <span class="number">1</span>))</span><br><span class="line">    MySphere = sphere_from_vector_and_scalar(PointArray, radius)</span><br><span class="line">    <span class="comment"># 获取它的Shape，从而通过display的函数来上色</span></span><br><span class="line">    MySphereShape_2 = MySphere.Shape()</span><br><span class="line"></span><br><span class="line">    FusedSpheres = BRepAlgoAPI_Fuse(MySphereShape_1, MySphereShape_2)</span><br><span class="line">    FusedSpheres_shape = FusedSpheres.Shape()</span><br><span class="line"></span><br><span class="line">    display.DisplayColoredShape(FusedSpheres_shape, <span class="string">"YELLOW"</span>)</span><br><span class="line"></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">erase_all</span><span class="params">(event=None)</span>:</span></span><br><span class="line">    display.EraseAll() <span class="comment">#display直接去除所有</span></span><br><span class="line"></span><br><span class="line"><span class="keyword">if</span> __name__ == <span class="string">'__main__'</span>:</span><br><span class="line">    display, start_display, add_menu, add_function_to_menu = init_display()  <span class="comment"># OCC.Display.SimpleGui.init_display()返回四个函数</span></span><br><span class="line">    <span class="comment">#四个函数分别是：display, start_display用于开启，add_menu用于增加菜单栏选项，add_funciton_to_menu用于给选项设置相应功能</span></span><br><span class="line">    add_menu(<span class="string">"File"</span>)</span><br><span class="line">    add_function_to_menu(<span class="string">'File'</span>,exit) <span class="comment">#参数1是菜单选项名，参数2是自定义的函数名，注意不加括号</span></span><br><span class="line">    add_menu(<span class="string">"Draw"</span>)</span><br><span class="line">    add_function_to_menu(<span class="string">'Draw'</span>,draw_sphere_1)</span><br><span class="line">    add_function_to_menu(<span class="string">'Draw'</span>,draw_sphere_2)</span><br><span class="line">    add_menu(<span class="string">'Boolean'</span>)</span><br><span class="line">    add_function_to_menu(<span class="string">'Boolean'</span>, draw_cutted_spheres_1)</span><br><span class="line">    add_function_to_menu(<span class="string">'Boolean'</span>, draw_cutted_spheres_2)</span><br><span class="line">    add_function_to_menu(<span class="string">'Boolean'</span>, draw_common_spheres)</span><br><span class="line">    add_function_to_menu(<span class="string">'Boolean'</span>, draw_fused_spheres)</span><br><span class="line">    add_menu(<span class="string">'Erase'</span>)</span><br><span class="line">    add_function_to_menu(<span class="string">'Erase'</span>,erase_all)</span><br><span class="line"></span><br><span class="line">    start_display()</span><br></pre></td></tr></table></figure>
<p>并集结果图：<br><img src="https://imgvideoforblog.oss-cn-shanghai.aliyuncs.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202020-04-06%20%E4%B8%8B%E5%8D%886.14.58.png" alt="alt"></p>
<p>结合两个球体的方式都一样，小结如下：<br>1.Construct Primitive_1<br>2. Create the shape Shape_1 = Primitive_1.Shape()<br>3. Construct Primitive_2<br>4. Create the shape Shape_2 = Primitive_2.Shape()<br>5. Perform the Boolean operation between Shape_1 and Shape_2 to get a New_Object<br>6. Create New_Object.Shape() before displaying it<br><br></p>
<h1 id="圆柱体"><a href="#圆柱体" class="headerlink" title="圆柱体"></a>圆柱体</h1><h2 id="大致思路"><a href="#大致思路" class="headerlink" title="大致思路"></a>大致思路</h2><p>如果直接调用API函数，需要传入的参数是（坐标系，圆半径，长度）。这个坐标系由<strong>新坐标系原点+z轴方向单位向量</strong>组成，注意这个z轴方向单位向量必须是<strong>从原点出发</strong>的。但我们一般的输入习惯是输入图形起始点和从该起始点的方向向量（还不一定单位化），所以需要自定义函数来处理输入，即封装API函数。</p>
<h2 id="注意方向向量"><a href="#注意方向向量" class="headerlink" title="注意方向向量"></a>注意方向向量</h2><p>方向向量显然是从原点出发，作为一个方向的指向。我们注意输入API函数时，方向向量一定要进行单位化（即NormVector函数）。<br>对于以下圆柱体的代码，我们选择先去用起点+单位化后的方向向量<em>长度，得到终点的位置，然后终点-起点得到方向向量，再单位化。其实这个操作复杂化了，*只需要将输入的方向向量单位化，然后直接拿去与起始点建立新坐标系即可。</em></p>
<h2 id="代码"><a href="#代码" class="headerlink" title="代码"></a>代码</h2><figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br><span class="line">55</span><br><span class="line">56</span><br><span class="line">57</span><br><span class="line">58</span><br><span class="line">59</span><br><span class="line">60</span><br><span class="line">61</span><br><span class="line">62</span><br><span class="line">63</span><br><span class="line">64</span><br><span class="line">65</span><br><span class="line">66</span><br><span class="line">67</span><br><span class="line">68</span><br><span class="line">69</span><br><span class="line">70</span><br><span class="line">71</span><br><span class="line">72</span><br><span class="line">73</span><br><span class="line">74</span><br><span class="line">75</span><br><span class="line">76</span><br><span class="line">77</span><br><span class="line">78</span><br><span class="line">79</span><br><span class="line">80</span><br><span class="line">81</span><br><span class="line">82</span><br><span class="line">83</span><br><span class="line">84</span><br><span class="line">85</span><br><span class="line">86</span><br><span class="line">87</span><br><span class="line">88</span><br><span class="line">89</span><br><span class="line">90</span><br><span class="line">91</span><br><span class="line">92</span><br><span class="line">93</span><br><span class="line">94</span><br><span class="line">95</span><br><span class="line">96</span><br><span class="line">97</span><br><span class="line">98</span><br><span class="line">99</span><br><span class="line">100</span><br><span class="line">101</span><br><span class="line">102</span><br><span class="line">103</span><br><span class="line">104</span><br><span class="line">105</span><br><span class="line">106</span><br><span class="line">107</span><br><span class="line">108</span><br><span class="line">109</span><br><span class="line">110</span><br><span class="line">111</span><br><span class="line">112</span><br><span class="line">113</span><br><span class="line">114</span><br><span class="line">115</span><br><span class="line">116</span><br><span class="line">117</span><br><span class="line">118</span><br><span class="line">119</span><br><span class="line">120</span><br><span class="line">121</span><br><span class="line">122</span><br><span class="line">123</span><br><span class="line">124</span><br><span class="line">125</span><br><span class="line">126</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> scipy</span><br><span class="line"><span class="keyword">import</span> sys</span><br><span class="line"><span class="keyword">from</span> OCC.Display.SimpleGui <span class="keyword">import</span> *</span><br><span class="line"><span class="keyword">from</span> OCC.Core.BRepPrimAPI <span class="keyword">import</span> *</span><br><span class="line"><span class="keyword">from</span> OCC.Core.BRepAlgoAPI <span class="keyword">import</span> *</span><br><span class="line"><span class="keyword">from</span> OCC.Core.gp <span class="keyword">import</span> *</span><br><span class="line"></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">length_column_vector</span><span class="params">(a)</span>:</span></span><br><span class="line">    <span class="string">"""</span></span><br><span class="line"><span class="string">    Compute length of column vector with 3 rows</span></span><br><span class="line"><span class="string"></span></span><br><span class="line"><span class="string">    @param a: column vector</span></span><br><span class="line"><span class="string">    @type  a: scipy array(3,1)</span></span><br><span class="line"><span class="string">    @return: length column vector</span></span><br><span class="line"><span class="string"></span></span><br><span class="line"><span class="string">    sample:</span></span><br><span class="line"><span class="string"></span></span><br><span class="line"><span class="string">       &gt;&gt;&gt; a = scipy.array([-3.0, 0.0, 4.0])</span></span><br><span class="line"><span class="string">       &gt;&gt;&gt; a = scipy.reshape(a,(3,1))</span></span><br><span class="line"><span class="string">       &gt;&gt;&gt; a</span></span><br><span class="line"><span class="string">       array([[-3.],</span></span><br><span class="line"><span class="string">              [ 0.],</span></span><br><span class="line"><span class="string">              [ 4.]])</span></span><br><span class="line"><span class="string">       &gt;&gt;&gt; length_column_vector(a)</span></span><br><span class="line"><span class="string">       5.0</span></span><br><span class="line"><span class="string">    """</span></span><br><span class="line">    <span class="keyword">return</span> ( scipy.sqrt( a[<span class="number">0</span>,<span class="number">0</span>] * a[<span class="number">0</span>,<span class="number">0</span>] + a[<span class="number">1</span>,<span class="number">0</span>] * a[<span class="number">1</span>,<span class="number">0</span>] + a[<span class="number">2</span>,<span class="number">0</span>] * a[<span class="number">2</span>,<span class="number">0</span>] ) )</span><br><span class="line"></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">NormVector</span><span class="params">(Vector)</span>:</span></span><br><span class="line">    <span class="string">"""</span></span><br><span class="line"><span class="string">    Normalize column vector with 3 rows.</span></span><br><span class="line"><span class="string"></span></span><br><span class="line"><span class="string">    @param Vector: column vector with 3 rows.</span></span><br><span class="line"><span class="string">    @type  Vector: scipy array(3,1)</span></span><br><span class="line"><span class="string">    @return: normalized vector</span></span><br><span class="line"><span class="string"></span></span><br><span class="line"><span class="string">    sample:</span></span><br><span class="line"><span class="string"></span></span><br><span class="line"><span class="string">       &gt;&gt;&gt; Vektor = scipy.array([-4.0, -2.0, 4.0])</span></span><br><span class="line"><span class="string">       &gt;&gt;&gt; Vektor = scipy.reshape(Vektor,(3,1))</span></span><br><span class="line"><span class="string">       &gt;&gt;&gt; Vektor</span></span><br><span class="line"><span class="string">       array([[-4.],</span></span><br><span class="line"><span class="string">              [-2.],</span></span><br><span class="line"><span class="string">              [ 4.]])</span></span><br><span class="line"><span class="string">       &gt;&gt;&gt; NormVector(Vektor)</span></span><br><span class="line"><span class="string">       array([[-0.66666667],</span></span><br><span class="line"><span class="string">              [-0.33333333],</span></span><br><span class="line"><span class="string">              [ 0.66666667]])</span></span><br><span class="line"><span class="string">    """</span></span><br><span class="line">    <span class="keyword">return</span>( ( <span class="number">1.0</span> / length_column_vector(Vector) ) * Vector )</span><br><span class="line"></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">cylinder_from_point_directionvector_length_and_radius</span><span class="params">( vector,directionvector,length,radius )</span>:</span></span><br><span class="line">    <span class="string">"""</span></span><br><span class="line"><span class="string">    画圆柱体的API函数OCC.Core.BRepPrimAPI.BRepPrimAPI_MakeCylinder的参数：</span></span><br><span class="line"><span class="string">    坐标系（由原点坐标+z轴方向单位向量组成），圆半径，长度</span></span><br><span class="line"><span class="string">    此自定义封装函数的意义在于，我需要传入的前两个参数是"起始点"和"方向向量"</span></span><br><span class="line"><span class="string">    那么这个函数的作用在于，把起始点和方向向量组装转换成坐标系。</span></span><br><span class="line"><span class="string">    """</span></span><br><span class="line">    <span class="comment"># Normalize the direction</span></span><br><span class="line">    directionunitvector = NormVector(directionvector)</span><br><span class="line">    <span class="comment"># determine the second point</span></span><br><span class="line">    vector2 = vector + length * directionunitvector <span class="comment">#终点的坐标表示</span></span><br><span class="line">    <span class="comment"># components of vector in float values</span></span><br><span class="line">    X1 = float( vector[ <span class="number">0</span>, <span class="number">0</span>] )</span><br><span class="line">    Y1 = float( vector[ <span class="number">1</span>, <span class="number">0</span>] )</span><br><span class="line">    Z1 = float( vector[ <span class="number">2</span>, <span class="number">0</span>] )</span><br><span class="line">    <span class="comment"># components of vector2 in float values</span></span><br><span class="line">    X2 = float( vector2[ <span class="number">0</span>, <span class="number">0</span>] )</span><br><span class="line">    Y2 = float( vector2[ <span class="number">1</span>, <span class="number">0</span>] )</span><br><span class="line">    Z2 = float( vector2[ <span class="number">2</span>, <span class="number">0</span>] )</span><br><span class="line"></span><br><span class="line">    <span class="comment"># 终点坐标减去起点坐标，即得到从原点出发的方向向量</span></span><br><span class="line">    directionP1P2 = scipy.array([ ( X2 - X1 ),</span><br><span class="line">    ( Y2 - Y1 ),</span><br><span class="line">    ( Z2 - Z1 ) ])</span><br><span class="line">    directionP1P2 = scipy.reshape( directionP1P2,(<span class="number">3</span>,<span class="number">1</span>))</span><br><span class="line">    <span class="comment"># 记得将该方向向量单位化</span></span><br><span class="line">    directionP1P2 = NormVector(directionP1P2)</span><br><span class="line">    <span class="comment"># origin at point 1 with gp_Pnt 新坐标系的原点</span></span><br><span class="line">    origin_local_coordinate_system = gp_Pnt(X1, Y1, Z1)</span><br><span class="line">    <span class="comment"># z-direction of the local coordinate system with gp_Dir 新坐标系的z轴方向单位向量</span></span><br><span class="line">    z_direction_local_coordinate_system = gp_Dir(directionP1P2[<span class="number">0</span>, <span class="number">0</span>],</span><br><span class="line">                                                        directionP1P2[<span class="number">1</span>, <span class="number">0</span>],</span><br><span class="line">                                                        directionP1P2[<span class="number">2</span>, <span class="number">0</span>])</span><br><span class="line">    <span class="comment"># local coordinate system with OCC.gp.gp_Ax2</span></span><br><span class="line">    local_coordinate_system = gp_Ax2(origin_local_coordinate_system,</span><br><span class="line">                                            z_direction_local_coordinate_system)</span><br><span class="line">    <span class="comment"># create cylinder utilising BRepPrimAPI_MakeCylinder</span></span><br><span class="line">    cylinder = BRepPrimAPI_MakeCylinder(local_coordinate_system,</span><br><span class="line">                                                        radius,</span><br><span class="line">                                                        length)</span><br><span class="line">    <span class="comment"># return cylinder</span></span><br><span class="line">    <span class="keyword">return</span> cylinder</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">draw_cylinder</span><span class="params">(event=None)</span>:</span></span><br><span class="line">    r = <span class="number">50.0</span></span><br><span class="line">    length = <span class="number">200.0</span></span><br><span class="line">    point = scipy.array([<span class="number">45.0</span>, <span class="number">80.0</span>, <span class="number">50.0</span>])</span><br><span class="line">    point = scipy.reshape(point,(<span class="number">3</span>,<span class="number">1</span>))</span><br><span class="line">    DirectionFromPoint = scipy.array([<span class="number">25.0</span>, <span class="number">50.0</span>, <span class="number">150.0</span>])</span><br><span class="line">    DirectionFromPoint = scipy.reshape(DirectionFromPoint, (<span class="number">3</span>,<span class="number">1</span>))</span><br><span class="line">    <span class="comment"># 画圆柱体的自定义函数的参数：起点、从起点到终点的方向向量、长度、圆半径</span></span><br><span class="line">    cylinder = cylinder_from_point_directionvector_length_and_radius(point, DirectionFromPoint, length, r)</span><br><span class="line">    cylinder_shape = cylinder.Shape()</span><br><span class="line">    display.DisplayColoredShape(cylinder_shape, <span class="string">"YELLOW"</span>)</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">erase_all</span><span class="params">(event=None)</span>:</span></span><br><span class="line">    display.EraseAll() <span class="comment">#display直接去除所有</span></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">exit</span><span class="params">(event=None)</span>:</span></span><br><span class="line">    sys.exit()</span><br><span class="line"></span><br><span class="line"><span class="keyword">if</span> __name__ == <span class="string">'__main__'</span>:</span><br><span class="line">    display, start_display, add_menu, add_function_to_menu = init_display()  <span class="comment"># OCC.Display.SimpleGui.init_display()返回四个函数</span></span><br><span class="line">    <span class="comment">#四个函数分别是：display, start_display用于开启，add_menu用于增加菜单栏选项，add_funciton_to_menu用于给菜单选项下拉框加选项</span></span><br><span class="line">    add_menu(<span class="string">"File"</span>)</span><br><span class="line">    add_function_to_menu(<span class="string">'File'</span>,exit) <span class="comment">#参数1是菜单选项名，参数2是自定义的函数名，注意不加括号</span></span><br><span class="line">    add_menu(<span class="string">"Draw"</span>)</span><br><span class="line">    add_function_to_menu(<span class="string">'Draw'</span>,draw_cylinder)</span><br><span class="line">    add_menu(<span class="string">'Erase'</span>)</span><br><span class="line">    add_function_to_menu(<span class="string">'Erase'</span>,erase_all)</span><br><span class="line"></span><br><span class="line">    start_display()</span><br></pre></td></tr></table></figure>
<br>

<h1 id="圆锥体"><a href="#圆锥体" class="headerlink" title="圆锥体"></a>圆锥体</h1><h2 id="大致思路-1"><a href="#大致思路-1" class="headerlink" title="大致思路"></a>大致思路</h2><p>画圆锥体的自定义函数的参数：起点、从原点出发的方向向量、长度、底圆半径、上圆半径。<br>注意我们这里就不冗余操作了，直接单位化方向向量后直接传入。</p>
<h2 id="代码-1"><a href="#代码-1" class="headerlink" title="代码"></a>代码</h2><figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br><span class="line">55</span><br><span class="line">56</span><br><span class="line">57</span><br><span class="line">58</span><br><span class="line">59</span><br><span class="line">60</span><br><span class="line">61</span><br><span class="line">62</span><br><span class="line">63</span><br><span class="line">64</span><br><span class="line">65</span><br><span class="line">66</span><br><span class="line">67</span><br><span class="line">68</span><br><span class="line">69</span><br><span class="line">70</span><br><span class="line">71</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">cone_from_point_height_directionvector_and_two_radii</span><span class="params">(vector,</span></span></span><br><span class="line"><span class="function"><span class="params">                                                         directionvector,</span></span></span><br><span class="line"><span class="function"><span class="params">                                                         height,</span></span></span><br><span class="line"><span class="function"><span class="params">                                                         radius1,</span></span></span><br><span class="line"><span class="function"><span class="params">                                                         radius2)</span>:</span></span><br><span class="line">    <span class="string">"""</span></span><br><span class="line"><span class="string">    Creates a cone OCC.BRepPrimAPI.BRepPrimAPI_MakeCone.</span></span><br><span class="line"><span class="string">    这里输入的directionvector是从原点出发的，所以不用计算终点再-起点，而直接单位化后即可</span></span><br><span class="line"><span class="string">    @param vector: vector at the beginning</span></span><br><span class="line"><span class="string">    @type  vector: scipy array(3,1)</span></span><br><span class="line"><span class="string">    @param directionvector: direction vector of the cone maina axis</span></span><br><span class="line"><span class="string">    @type  directionvector: scipy array(3,1)</span></span><br><span class="line"><span class="string">    @param height: cone height</span></span><br><span class="line"><span class="string">    @type  height: float</span></span><br><span class="line"><span class="string">    @param radius1: radius at the cone bottom</span></span><br><span class="line"><span class="string">    @type  radius1: float</span></span><br><span class="line"><span class="string">    @param radius1: cone tip radius</span></span><br><span class="line"><span class="string">    @type  radius1: float</span></span><br><span class="line"><span class="string">    @return: cone</span></span><br><span class="line"><span class="string">    """</span></span><br><span class="line">    <span class="comment"># Normalize the direction 单位化方向向量</span></span><br><span class="line">    directionunitvector = NormVector(directionvector)</span><br><span class="line">    <span class="comment"># Determine the second point</span></span><br><span class="line">    vector2 = vector + height * directionunitvector</span><br><span class="line">    <span class="comment"># components in floats</span></span><br><span class="line">    X1 = float(vector[<span class="number">0</span>, <span class="number">0</span>])</span><br><span class="line">    Y1 = float(vector[<span class="number">1</span>, <span class="number">0</span>])</span><br><span class="line">    Z1 = float(vector[<span class="number">2</span>, <span class="number">0</span>])</span><br><span class="line">    <span class="comment"># components in floats</span></span><br><span class="line">    X2 = float(directionunitvector[<span class="number">0</span>, <span class="number">0</span>])</span><br><span class="line">    Y2 = float(directionunitvector[<span class="number">1</span>, <span class="number">0</span>])</span><br><span class="line">    Z2 = float(directionunitvector[<span class="number">2</span>, <span class="number">0</span>])</span><br><span class="line">    <span class="comment"># create gp_Pnt-point</span></span><br><span class="line">    P1 = gp_Pnt(X1, Y1, Z1)</span><br><span class="line">    <span class="comment"># Read the direction unit vector (has to be done, but I do not know why)</span></span><br><span class="line">    directionunit = scipy.array([(X2),</span><br><span class="line">                                 (Y2),</span><br><span class="line">                                 (Z2)])</span><br><span class="line">    directionunit = scipy.reshape(directionunit, (<span class="number">3</span>, <span class="number">1</span>))</span><br><span class="line">    <span class="comment"># normalize - to be sure</span></span><br><span class="line">    directionunit = NormVector(directionunit)</span><br><span class="line">    <span class="comment"># origin at point 1 with gp_Pnt 新坐标系的原点</span></span><br><span class="line">    origin_local_coordinate_system = P1</span><br><span class="line">    <span class="comment"># z-direction of the local coordinate system 新坐标系的方向单位向量</span></span><br><span class="line">    z_direction_local_coordinate_system = gp_Dir(directionunit[<span class="number">0</span>, <span class="number">0</span>],</span><br><span class="line">                                                        directionunit[<span class="number">1</span>, <span class="number">0</span>],</span><br><span class="line">                                                        directionunit[<span class="number">2</span>, <span class="number">0</span>])</span><br><span class="line">    <span class="comment"># 用gp_Ax2函数建立一个新的坐标系</span></span><br><span class="line">    local_coordinate_system = gp_Ax2(origin_local_coordinate_system,</span><br><span class="line">                                            z_direction_local_coordinate_system)</span><br><span class="line"></span><br><span class="line">    <span class="comment"># create cone utilising BRepPrimAPI.BRepPrimAPI_MakeCone</span></span><br><span class="line">    cone = BRepPrimAPI_MakeCone(local_coordinate_system,</span><br><span class="line">                                                radius1,</span><br><span class="line">                                                radius2,</span><br><span class="line">                                                height)</span><br><span class="line">    <span class="comment"># return cone</span></span><br><span class="line">    <span class="keyword">return</span> cone</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">draw_cone</span><span class="params">(envent=None)</span>:</span></span><br><span class="line">    r1 = <span class="number">50.0</span></span><br><span class="line">    r2 = <span class="number">0.0</span></span><br><span class="line">    length = <span class="number">50.0</span></span><br><span class="line">    point = scipy.array([<span class="number">45.0</span>, <span class="number">80.0</span>, <span class="number">50.0</span>])</span><br><span class="line">    point = scipy.reshape(point, (<span class="number">3</span>, <span class="number">1</span>))</span><br><span class="line">    DirectionFromPoint = scipy.array([<span class="number">25.0</span>, <span class="number">50.0</span>, <span class="number">150.0</span>])</span><br><span class="line">    DirectionFromPoint = scipy.reshape(DirectionFromPoint, (<span class="number">3</span>, <span class="number">1</span>))</span><br><span class="line">    <span class="comment"># 画圆锥体的自定义函数的参数：起点、从原点出发的方向向量、长度、底圆半径、上圆半径</span></span><br><span class="line">    cone = cone_from_point_height_directionvector_and_two_radii(point, DirectionFromPoint, length, r1, r2)</span><br><span class="line">    cone_shape = cone.Shape()</span><br><span class="line">    display.DisplayColoredShape(cone_shape, <span class="string">"YELLOW"</span>)</span><br></pre></td></tr></table></figure>
<Br>

<h1 id="箭头"><a href="#箭头" class="headerlink" title="箭头"></a>箭头</h1><h2 id="大致思路-2"><a href="#大致思路-2" class="headerlink" title="大致思路"></a>大致思路</h2><p>箭头的API函数是？没有！自己想想，箭头就是由一个圆柱体+一个圆锥体（上圆半径=0.0）来构成的。<br>所以，根据我们输入的习惯，我们假设要输入的参数包括：箭头的起始点、箭头的方向向量、箭头的总长、箭头的头(head)的长度、箭头的箭(shaft)的圆半径、箭头的头(head)的底圆半径。</p>
<p>那么，再来结合之前定义好的圆柱体、圆锥体的自定义函数，只需要手动计算两个元素：<br>①圆柱体的长度，用箭头的总长-head的长度<br>②圆锥体的起始点，用箭头的起始点+单位化后的方向向量*圆柱体的长度</p>
<h2 id="代码-2"><a href="#代码-2" class="headerlink" title="代码"></a>代码</h2><figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br><span class="line">55</span><br><span class="line">56</span><br><span class="line">57</span><br><span class="line">58</span><br><span class="line">59</span><br><span class="line">60</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">arrowCreate</span><span class="params">( vector,</span></span></span><br><span class="line"><span class="function"><span class="params">                directionvector,</span></span></span><br><span class="line"><span class="function"><span class="params">                arrowlength,</span></span></span><br><span class="line"><span class="function"><span class="params">                radius_of_arrow_shaft,</span></span></span><br><span class="line"><span class="function"><span class="params">                lenght_of_arrow_head,</span></span></span><br><span class="line"><span class="function"><span class="params">                radius_of_arrow_head )</span>:</span></span><br><span class="line">    <span class="string">'''</span></span><br><span class="line"><span class="string">    Function arrowshape creates the shape of an arrow starting at vector</span></span><br><span class="line"><span class="string">    pointing into diretcion. We create a cylinder and a cone and combine the</span></span><br><span class="line"><span class="string">    utilising BRepAlgoAPI.BRepAlgoAPI_Fuse.</span></span><br><span class="line"><span class="string"></span></span><br><span class="line"><span class="string">    @param vector: starting point of the arrow</span></span><br><span class="line"><span class="string">    @type  vector: scipy array(3,1)</span></span><br><span class="line"><span class="string">    @param directionvector: direction of the arrow</span></span><br><span class="line"><span class="string">    @type  directionvector: scipy  array(3,1)</span></span><br><span class="line"><span class="string">    @param arrowlength: length of the arrow</span></span><br><span class="line"><span class="string">    @type  arrowlength: scalar</span></span><br><span class="line"><span class="string">    @param radius_of_arrow_shaft: radius of the arrow shaft</span></span><br><span class="line"><span class="string">    @type  radius_of_arrow_shaft: scalar</span></span><br><span class="line"><span class="string">    @param lenght_of_arrow_head: length of the arrow head</span></span><br><span class="line"><span class="string">    @type  lenght_of_arrow_head: scalar</span></span><br><span class="line"><span class="string">    @param radius_of_arrow_head: radius of the arrow head</span></span><br><span class="line"><span class="string">    @type  radius_of_arrow_head: scalar</span></span><br><span class="line"><span class="string">    @return: Pfeil als Shape Objekt</span></span><br><span class="line"><span class="string">    '''</span></span><br><span class="line">    <span class="comment"># Normalize the direction</span></span><br><span class="line">    directionunitvector = NormVector(directionvector)</span><br><span class="line">    <span class="comment"># the shaft length</span></span><br><span class="line">    cylinder_length = arrowlength - lenght_of_arrow_head</span><br><span class="line">    <span class="comment"># create shaft</span></span><br><span class="line">    arrow_shaft = cylinder_from_point_directionvector_length_and_radius( \</span><br><span class="line">                                                    vector,</span><br><span class="line">                                                    directionunitvector,</span><br><span class="line">                                                    cylinder_length,</span><br><span class="line">                                                    radius_of_arrow_shaft )</span><br><span class="line">    arrow_shaft_Shape = arrow_shaft.Shape()</span><br><span class="line">    <span class="comment"># begin of arrow head (flat suface)</span></span><br><span class="line">    arrow_head_point = vector + cylinder_length * directionunitvector</span><br><span class="line">    <span class="comment"># create arrow head</span></span><br><span class="line">    arrow_head = cone_from_point_height_directionvector_and_two_radii(  \</span><br><span class="line">                                                    arrow_head_point,</span><br><span class="line">                                                    directionunitvector,</span><br><span class="line">                                                    lenght_of_arrow_head,</span><br><span class="line">                                                    radius_of_arrow_head,</span><br><span class="line">                                                    <span class="number">0.0</span> ) <span class="comment">#圆锥体上圆半径=0</span></span><br><span class="line">    arrow_head_Shape = arrow_head.Shape()</span><br><span class="line">    <span class="comment"># combine shaft and head</span></span><br><span class="line">    arrow = BRepAlgoAPI_Fuse(   arrow_shaft_Shape,</span><br><span class="line">                                                arrow_head_Shape )</span><br><span class="line">    <span class="keyword">return</span> arrow</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">draw_arrow</span><span class="params">(envent=None)</span>:</span></span><br><span class="line">    point = scipy.array([<span class="number">45.0</span>, <span class="number">80.0</span>, <span class="number">50.0</span>])</span><br><span class="line">    point = scipy.reshape(point, (<span class="number">3</span>, <span class="number">1</span>))</span><br><span class="line">    DirectionFromPoint = scipy.array([<span class="number">25.0</span>, <span class="number">50.0</span>, <span class="number">150.0</span>])</span><br><span class="line">    DirectionFromPoint = scipy.reshape(DirectionFromPoint, (<span class="number">3</span>, <span class="number">1</span>))</span><br><span class="line">    <span class="comment"># 画箭头的自定义函数的参数：起始点、方向向量、箭头总长、箭的圆半径、头的长度、头的圆半径</span></span><br><span class="line">    arrow = arrowCreate(point, DirectionFromPoint, <span class="number">100</span>, <span class="number">30</span>, <span class="number">30</span>, <span class="number">40</span>)</span><br><span class="line">    arrow_shape = arrow.Shape()</span><br><span class="line">    display.DisplayColoredShape(arrow_shape, <span class="string">"YELLOW"</span>)</span><br></pre></td></tr></table></figure>
<p>这里注意头的圆半径要大于箭的圆半径，否则就不是箭头了。。</p>
<br>

<h1 id="坐标系"><a href="#坐标系" class="headerlink" title="坐标系"></a>坐标系</h1><p>创建一个三维坐标系。</p>
<h2 id="大致思路-3"><a href="#大致思路-3" class="headerlink" title="大致思路"></a>大致思路</h2><p>思考组成元素：<strong>原点（球体）、xyz三个坐标轴（三个箭头）。</strong></p>
<p>注意在创建x坐标轴（箭头）的时候，起始点写成origin-0.5<em>arrow_length</em>xDir，即往后退一半长度，这样才会有“穿插”的效果。</p>
<p>另外，其实可以直接在该函数中进行display直接展示，再另写个函数传参即可。注意display不用当做参数传入函数的，直接调用即可，因为主函数中第一句话：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">display, start_display, add_menu, add_function_to_menu = init_display()</span><br></pre></td></tr></table></figure>
<p>可以理解成display全局都可使用了。</p>
<h2 id="代码-3"><a href="#代码-3" class="headerlink" title="代码"></a>代码</h2><p>这里要用到之前的所有函数，这里省略定义。</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">CoordinateCross</span><span class="params">( centerpoint_sphere_radius,</span></span></span><br><span class="line"><span class="function"><span class="params">                     arrow_length,</span></span></span><br><span class="line"><span class="function"><span class="params">                     radius_of_arrow_shaft,</span></span></span><br><span class="line"><span class="function"><span class="params">                     length_of_arrow_head,</span></span></span><br><span class="line"><span class="function"><span class="params">                     radius_of_arrow_head)</span>:</span></span><br><span class="line">    <span class="string">'''</span></span><br><span class="line"><span class="string">    创建一个多彩的3维坐标系</span></span><br><span class="line"><span class="string">    :param centerpoint_sphere_radius: 原点球体的半径</span></span><br><span class="line"><span class="string">    :param arrow_length: 箭头总长</span></span><br><span class="line"><span class="string">    :param radius_of_arrow_shaft: 箭的半径</span></span><br><span class="line"><span class="string">    :param length_of_arrow_head:  头的长度</span></span><br><span class="line"><span class="string">    :param radius_of_arrow_head:  头的半径</span></span><br><span class="line"><span class="string">    '''</span></span><br><span class="line">    <span class="comment"># 原点坐标</span></span><br><span class="line">    origin = scipy.zeros((<span class="number">3</span>,<span class="number">1</span>),dtype=float)</span><br><span class="line">    <span class="comment"># x轴方向</span></span><br><span class="line">    xDir = scipy.zeros((<span class="number">3</span>,<span class="number">1</span>),dtype=float)</span><br><span class="line">    xDir[<span class="number">0</span>,<span class="number">0</span>] = <span class="number">1.0</span></span><br><span class="line">    <span class="comment"># y轴方向</span></span><br><span class="line">    yDir = scipy.zeros((<span class="number">3</span>,<span class="number">1</span>),dtype=float)</span><br><span class="line">    yDir[<span class="number">1</span>,<span class="number">0</span>] = <span class="number">1.0</span></span><br><span class="line">    <span class="comment"># z轴方向</span></span><br><span class="line">    zDir = scipy.zeros((<span class="number">3</span>,<span class="number">1</span>),dtype=float)</span><br><span class="line">    zDir[<span class="number">2</span>,<span class="number">0</span>] = <span class="number">1.0</span></span><br><span class="line"></span><br><span class="line">    <span class="comment">#创建原点（球体）</span></span><br><span class="line">    OriginSphere = sphere_from_vector_and_scalar(origin, centerpoint_sphere_radius)</span><br><span class="line">    OriginSphere_Shape = OriginSphere.Shape()</span><br><span class="line"></span><br><span class="line">    <span class="comment">#创建x轴（箭头） 注意起始点往后退一半的长度，这样才能穿插</span></span><br><span class="line">    xAxis = arrowCreate(origin<span class="number">-0.5</span>*arrow_length*xDir, xDir, arrow_length, radius_of_arrow_shaft, length_of_arrow_head, radius_of_arrow_head)</span><br><span class="line">    xAxis_Shape = xAxis.Shape()</span><br><span class="line">    <span class="comment"># 创建y轴（箭头） 注意起始点往后退一半的长度，这样才能穿插 同上，只需改方向向量</span></span><br><span class="line">    yAxis = arrowCreate(origin - <span class="number">0.5</span> * arrow_length * yDir, yDir, arrow_length, radius_of_arrow_shaft, length_of_arrow_head,</span><br><span class="line">                        radius_of_arrow_head)</span><br><span class="line">    yAxis_Shape = yAxis.Shape()</span><br><span class="line">    <span class="comment"># 创建z轴（箭头） 注意起始点往后退一半的长度，这样才能穿插 同上，只需改方向向量</span></span><br><span class="line">    zAxis = arrowCreate(origin - <span class="number">0.5</span> * arrow_length * zDir, zDir, arrow_length, radius_of_arrow_shaft, length_of_arrow_head,</span><br><span class="line">                        radius_of_arrow_head)</span><br><span class="line">    zAxis_Shape = zAxis.Shape()</span><br><span class="line"></span><br><span class="line">    <span class="comment"># 画原点，画三条轴</span></span><br><span class="line">    display.DisplayColoredShape( OriginSphere_Shape, <span class="string">'WHITE'</span>)</span><br><span class="line">    display.DisplayColoredShape( xAxis_Shape, <span class="string">'BLUE'</span>)</span><br><span class="line">    display.DisplayColoredShape( yAxis_Shape, <span class="string">'ORANGE'</span>)</span><br><span class="line">    display.DisplayColoredShape( zAxis_Shape, <span class="string">'GREEN'</span>)</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">draw_coordinate</span><span class="params">(event=None)</span>:</span></span><br><span class="line">    CoordinateCross(centerpoint_sphere_radius=<span class="number">20</span>,</span><br><span class="line">                    arrow_length=<span class="number">500</span>,</span><br><span class="line">                    radius_of_arrow_shaft=<span class="number">10</span>,</span><br><span class="line">                    length_of_arrow_head=<span class="number">30</span>,</span><br><span class="line">                    radius_of_arrow_head=<span class="number">20</span>)</span><br></pre></td></tr></table></figure>
<p>结果图：<br><img src="https://imgvideoforblog.oss-cn-shanghai.aliyuncs.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202020-04-10%20%E4%B8%8B%E5%8D%881.31.30.png" alt="alt"></p>

      
    </div>
    <footer class="article-footer">
      <a data-url="http://yoursite.com/2020/04/10/pythonocc%E5%85%A5%E9%97%A8/" data-id="ck8u0hjjn0000496c6l5b26cy"
         class="article-share-link">Share</a>
      
  <ul class="article-tag-list" itemprop="keywords"><li class="article-tag-list-item"><a class="article-tag-list-link" href="/tags/%E7%BC%96%E7%A8%8B%E6%8A%80%E6%9C%AF/" rel="tag">编程技术</a></li></ul>

    </footer>

  </div>

  
    
  <nav class="article-nav">
    
    
      <a href="/2020/04/07/python%E7%BC%96%E7%A8%8B%E8%B8%A9%E5%9D%91%E8%AE%B0%E5%BD%95/" class="article-nav-link">
        <strong class="article-nav-caption">Olde posts</strong>
        <div class="article-nav-title">python编程踩坑记录</div>
      </a>
    
  </nav>


  

  
    
  <div class="gitalk" id="gitalk-container"></div>
  
<link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css">

  
<script src="https://unpkg.com/gitalk/dist/gitalk.min.js"></script>

  
<script src="https://cdn.bootcss.com/blueimp-md5/2.10.0/js/md5.min.js"></script>

  <script type="text/javascript">
    var gitalk = new Gitalk({
      clientID: 'dd9dd0a01eb6aea2b4b2',
      clientSecret: 'f10df8d5a64e14405c16d484ff17f526f1ff2c21',
      repo: 'gitalk_blog',
      owner: 'JosephLZD',
      admin: ['JosephLZD'],
      // id: location.pathname,      // Ensure uniqueness and length less than 50
      id: md5(location.pathname),
      distractionFreeMode: false,  // Facebook-like distraction free mode
      pagerDirection: 'last'
    })

  gitalk.render('gitalk-container')
  </script>

  

</article>



</section>
  <footer class="footer">
  <div class="outer">
    <div class="float-right">
      <ul class="list-inline">
  
    <li><i class="fe fe-smile-alt"></i> <span id="busuanzi_value_site_uv"></span></li>
  
</ul>
    </div>
    <ul class="list-inline">
      <li>&copy; 2020 Blog_JosephLZD</li>
      <li>Powered by <a href="http://hexo.io/" target="_blank">Hexo</a></li>
    </ul>
  </div>
</footer>

</main>

<aside class="sidebar sidebar-specter">
  
    <button class="navbar-toggle"></button>
<nav class="navbar">
  
    <div class="logo">
      <a href="/"><img src="/images/hexo.svg" alt="Blog_JosephLZD"></a>
    </div>
  
  <ul class="nav nav-main">
    
      <li class="nav-item">
        <a class="nav-item-link" href="/">Home</a>
      </li>
    
      <li class="nav-item">
        <a class="nav-item-link" href="/archives">Archive</a>
      </li>
    
      <li class="nav-item">
        <a class="nav-item-link" href="/gallery">Gallery</a>
      </li>
    
      <li class="nav-item">
        <a class="nav-item-link" href="/about">About</a>
      </li>
    
    <li class="nav-item">
      <a class="nav-item-link nav-item-search" title="搜索">
        <i class="fe fe-search"></i>
        Search
      </a>
    </li>
  </ul>
</nav>
<nav class="navbar navbar-bottom">
  <ul class="nav">
    <li class="nav-item">
      <div class="totop" id="totop">
  <i class="fe fe-rocket"></i>
</div>
    </li>
    <li class="nav-item">
      
        <a class="nav-item-link" target="_blank" href="/atom.xml" title="RSS Feed">
          <i class="fe fe-feed"></i>
        </a>
      
    </li>
  </ul>
</nav>
<div class="search-form-wrap">
  <div class="local-search local-search-plugin">
  <input type="search" id="local-search-input" class="local-search-input" placeholder="Search...">
  <div id="local-search-result" class="local-search-result"></div>
</div>
</div>
  </aside>
  
<script src="/js/jquery-2.0.3.min.js"></script>


<script src="/js/jquery.justifiedGallery.min.js"></script>


<script src="/js/lazyload.min.js"></script>


<script src="/js/busuanzi-2.3.pure.min.js"></script>


  
<script src="/fancybox/jquery.fancybox.min.js"></script>




  
<script src="/js/tocbot.min.js"></script>

  <script>
    // Tocbot_v4.7.0  http://tscanlin.github.io/tocbot/
    tocbot.init({
      tocSelector: '.tocbot',
      contentSelector: '.article-entry',
      headingSelector: 'h1, h2, h3, h4, h5, h6',
      hasInnerContainers: true,
      scrollSmooth: true,
      positionFixedSelector: '.tocbot',
      positionFixedClass: 'is-position-fixed',
      fixedSidebarOffset: 'auto',
    });
  </script>



<script src="/js/ocean.js"></script>


</body>
</html>